CREATE TABLE CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EXT_CUSTOMER_ID VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL
);

CREATE SEQUENCE "CUSTOMER_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

CREATE TABLE ADDRESS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    STREET VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL
);

 ALTER TABLE ADDRESS
    ADD FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(ID);

CREATE SEQUENCE "ADDRESS_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

CREATE TABLE CUSTOMER_PRODUCT (
    CUSTOMER_ID INT NOT NULL,
    PRODUCTS_ID VARCHAR(100) NOT NULL
);
