CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SKU VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100) NULL
);

ALTER TABLE PRODUCT ADD CONSTRAINT SKU_UNIQUE UNIQUE(SKU);

CREATE SEQUENCE "PRODUCT_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

